# Generated by Django 6.0.2 on 2026-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagallery',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
