# Generated by Django 6.0.2 on 2026-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_mediagallery_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('minutes', 'Meeting Minutes'), ('constitution', 'Constitution'), ('financial', 'Financial Report'), ('notice', 'Notice'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
