# Generated by Django 6.0.2 on 2026-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_document_document_type_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
