# Generated by Django 6.0.6 on 2026-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_document_content_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('event', 'Event'), ('payment', 'Payment'), ('meeting', 'Meeting')], default='general', max_length=20),
        ),
    ]
