# Generated by Django 6.0.2 on 2026-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('meeting', 'Meeting'), ('announcement', 'Announcement'), ('approval', 'Approval'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
