# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VillagePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_statuses', to='payments.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='accounts.village'),
        ),
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together={('payment_request', 'village')},
        ),
    ]
