# Generated by Django 6.0.2 on 2026-03-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_villagepaymentstatus_paymenttransaction_paid_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='villagepaymentstatus',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villagepaymentstatus',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villagepaymentstatus',
            name='payment_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='village_statuses', to='payments.paymentrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villagepaymentstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='villagepaymentstatus',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='accounts.village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_type',
            field=models.CharField(choices=[('monthly_dues', 'Monthly Dues'), ('event', 'Event Contribution'), ('levy', 'Levy'), ('fine', 'Fine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.village'),
        ),
        migrations.AlterUniqueTogether(
            name='villagepaymentstatus',
            unique_together={('payment_request', 'village')},
        ),
    ]
